spring:
  application:
    name: spring-payment
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9000

kafka:
  host: localhost
  port: 9092
  didan:
    server: ${kafka.host}:${kafka.port}
database:
  host: localhost
  port: 3306
  name: quarkus_payment
  username: root
  password: 17052002

client:
  endpoint:
    account-transaction: http://localhost:9010
  protocol: http

