spring:
  application:
    name: spring-payment
  datasource:
    url: jdbc:mysql://localhost:3306/quarkus_payment
    username: root
    password: 17052002
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9000

kafka:
  didan:
    server: localhost:9092

client:
  endpoint:
    account-transaction: http://localhost:9010
  protocol: http