apiVersion: apps/v1 # apiVersion dùng để deploy 1 ứng dụng
kind: Deployment # Loại cấu hình (Deployment) - dùng để deploy 1 ứng dụng
metadata:
  name: accountdb
  labels:
    app: accountdb
spec:
  selector:
    matchLabels:
      app: accountdb
  template:
    metadata:
      labels:
        app: accountdb
    spec:
      containers:
        - name: accountdb
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: accountdb
            - name: MYSQL_USER
              value: account
            - name: MYSQL_PASSWORD
              value: "mysql@123"
          ports:
            - containerPort: 3306
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: paymentdb
spec:
  selector:
    app: paymentdb
  type: LoadBalancer
  ports:
    - port: 3304
      targetPort: 3306
      protocol: TCP