spring:
  application:
    name: spring-account-transaction
  datasource:
    url: jdbc:mysql://localhost:3306/quarkus_account_transaction
    username: root
    password: 17052002
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 9010

kafka:
  server: localhost:9092
